;***********************************************************
;SAMPLE PIO
;***********************************************************
;
;PIO-PORTS:
SEGMENT	EQU	0F4h		;AUSGABE-PORT SEGMENTANSTEUERUNG
PIO1AC	EQU	0F6h
DIGITAP	EQU	0F5h		;B2...B7=DIGITANST. UND TASTENMATRIX
				;B0=TAPE-IN, B1=TAPE-OUT
PIO1BC	EQU	0F7h
USERPORT EQU	0F8h		;USER-PORT, FREI VERFUEGBAR
PI02AC	EQU	0FAh
KEYIN	EQU	0F9h		;B4...B7=EINGAENGE TASTEN-ABFRAGE
				;B0...B3 FUER USER NUTZBAR
PIO2BC	EQU	0FBh
;CTC-ADRESSEN
CTC0	EQU	0ECh
CTC1	EQU	0EDh
CTC2	EQU	0EEh
CTC3	EQU	0EFh
;VEREINBARUNGEN BEI ERWEITERUNGEN
INTVEK	EQU	00h		;INT-VECT. FUER CTC
HIINT	EQU	23h		;CPU-I-REG
;
	ORG	2000h
START:
	CALL	IOINIT
	LD	A,0FFh
	LD	E,11111011b	;BITMUSTER FUER DIGITANSTEUERUNG
LOOP:
	CALL	CONVERT
	CALL	ONESEG
	CALL	DISPLAY
	RL	E
	JP	LOOP
;
	ORG	2020h
;---------------------- IO-INITIALISIERUNG -----------
IOINIT:				;PIO-INITIALISIERUNG
	LD	A,0CFh		;MODE 3
	OUT	(PIO1AC),A	;SEGMENT-PORT
	LD	A,0FFh
	OUT	(SEGMENT),A	;ALLE SEGMENTE AUSSCHALTEN
	LD	A,00h		;E-A-DEFINITION
	OUT	(PIO1AC),A

	LD	A,0CFh		;MODE 3
	OUT	(PIO1BC),A	;DIGIT-AUSG.
				;B2...B7 = D-LSD,D-MSD,A-LSD...A-MSD
	LD	A,0FFh		;ALLE TREIBER SPERREN
	OUT	(DIGITAP),A
	LD	A,01h		;B0-EINGANG, B1...B7-AUSGAENGE
	OUT	(PIO1BC),A

	LD	A,0CFh		;MODE 3
	OUT	(PIO2BC),A	;TASTEN-EINGAENGE B4...B7
	LD	A,0FFh
	OUT	(PIO2BC),A
	RET
;
	ORG	2050h
;---------------------- LED DISPLAY AND KEYIN --------
DISPLAY:			;IN A<-DISPLAY_DATA, E<-BIT_PATTERN
				;OUT A<-KEYIN
	CPL
	OUT	(SEGMENT),A
	LD	A,E		;DIGIT ANSTEUERN
	OUT	(DIGITAP),A
	LD	B,100		;ZEITVERZOEGERUNG
	DJNZ	$
	IN	A,(KEYIN)	;TASTENWERT EINLESEN
	EX	AF,AF'
	LD	A,0FFh
	OUT	(DIGITAP),A	;ANZEIGE AUS
	EX	AF,AF'
	RET
;
	ORG	2070h
;--------------------- ONESEG -------------------------
ONESEG:
	PUSH	HL
	PUSH	DE
	LD	HL,SEGTAB	;ADR DER SEGMENTTABELLE
	AND	0Fh		;OBERES HALBBYTE AUSBLENDEN
	LD	E,A
	LD	D,0
	ADD	HL,DE
	LD	A,(HL)		;KONVERTIERTE ZAHL NACH A
	POP	DE
	POP	HL
	RET
;
	ORG	2090h
;--------------------- CONVERT ------------------------
CONVERT:
	CPL
	SRA	A
	SRA	A
	SRA	A
	SRA	A
	RET
;
	ORG	20B0h
;----------------------- CODE FUER HEX-ZIFFERN --------
SEGTAB:
	DEFB	0E7h		;0
	DEFB	21h		;1
	DEFB	0CDh		;2
	DEFB	0ADh		;3
	DEFB	2Bh		;4
	DEFB	0AEh		;5
	DEFB	0EEh		;6
	DEFB	25h		;7
	DEFB	0EFh		;8
	DEFB	0AFh		;9
	DEFB	6Fh		;A
	DEFB	0EAh		;B
	DEFB	0C6h		;C
	DEFB	0E9h		;D
	DEFB	0CEh		;E
	DEFB	4Eh		;F
	END
;
;***********************************************************
;【動作メモ】
;・7SEG表示は動作する
;・キー入力の適切な取得ができない (キーUPでイベント発生)
;***********************************************************
