;***********************************************************
;SAMPLE8
;***********************************************************
;
PIOAD	EQU	0D0h
PIOAC	EQU	0D1h
PIOBD	EQU	0D2h
PIOBC	EQU	0D3h
;
	ORG	0000h
START:
	LD	SP,0000h	;SP <- 0x0000
	LD	HL,INTPA	;PIO A CONTROL
	LD	B,3
	LD	C,PIOAC
	OTIR
	LD	HL,INTPB	;PIO B CONTROL
	LD	B,5
	LD	C,PIOBC
	OTIR
	LD	A,01h		;INTERRUPT SETTING
	LD	I,A
	IM	2
	EI
WAIT:
	JR	WAIT
INTPA:
	DEFB	0CFh		;MODE 3
	DEFB	00h		;ALL OUTPUT
	DEFB	07h		;ENABLE INTERRUPT
INTPB:
	DEFB	00h		;VECTOR ADDRESS
	DEFB	0CFh		;MODE 3
	DEFB	0FFh		;ALL INPUT
	DEFB	97h		;ENABLE INTERRUPT
	DEFB	00h		;MASK SETTING
;
	ORG	0100h
	DEFW	INT
INT:
	IN	A,(PIOBD)	;INPUT
	LD	C,0
	LD	B,8
LOOP8:
	RRA			;A <- A>>1
	JR	NC,DISP
	INC	C		;C <- C+1
	DJNZ	LOOP8
	EI
	RETI
DISP
	LD	A,C		;A <- C
	CALL	CONV
	OUT	(PIOAD),A	;OUTPUT
	EI
	RETI
;
CONV:
	AND	0Fh		;A <- A&0x0F
	LD	C,A		;C <- A
	LD	B,0		;B <- 0
	LD	HL,TABLE
	ADD	HL,BC		;HL <- BC
	LD	A,(HL)		;A <- (HL)
	RET
TABLE:
	DEFB	5Ch
	DEFB	06h
	DEFB	58h
	DEFB	4Fh
	DEFB	66h
	DEFB	6Dh
	DEFB	7Dh
	DEFB	27h
	DEFB	7Fh
	DEFB	6Fh
	DEFB	77h
	DEFB	7Ch
	DEFB	39h
	DEFB	5Eh
	DEFB	79h
	DEFB	71h
	END
